# Generated by Django 5.1.7 on 2025-04-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='00100-Nairobi, Kenya'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='254', max_length=100),
        ),
    ]
