# Generated by Django 5.1.2 on 2025-03-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='claim',
            name='health_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.healthplan'),
        ),
    ]
