# Generated by Django 5.1.7 on 2025-04-01 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SEND', 'Send'), ('RECEIVE', 'Receive'), ('WITHDRAW', 'Withdraw')], max_length=10)),
                ('currency', models.CharField(choices=[('QPT', 'QPT'), ('HBAR', 'HBAR')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recipient_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashgraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpt_public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('qpt_private_key', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('recipient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
